Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Enabled: false

AllCops:
  TargetRubyVersion: '2.4'
  Exclude:
    - Gemfile
    - db/*
    - test/*
    - test/**/*
    - config/**/*
    - bin/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb